config/routes.rb
Rails.application.routes.draw do
  resources :costs
  resources :hosts
  resources :posts
  root "posts#index"

  # get "posts", to: "posts#index"
  # get "posts/show", to: "posts#show"
  # get "posts/new", to: "posts#new"
  # get "posts/edit", to: "posts#edit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cost.rb
class Cost < ApplicationRecord
end

app/models/host.rb
class Host < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 10 }

  # validates_presence_of :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: %i[ show edit update destroy ]

  # GET /costs or /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1 or /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs or /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to cost_url(@cost), notice: "Cost was successfully created." }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1 or /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to cost_url(@cost), notice: "Cost was successfully updated." }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1 or /costs/1.json
  def destroy
    @cost.destroy

    respond_to do |format|
      format.html { redirect_to costs_url, notice: "Cost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cost_params
      params.require(:cost).permit(:title, :body, :age, :fav_color)
    end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: %i[ show edit update destroy ]

  # GET /hosts or /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1 or /hosts/1.json
  def show
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts or /hosts.json
  def create
    @host = Host.new(host_params)

    respond_to do |format|
      if @host.save
        format.html { redirect_to host_url(@host), notice: "Host was successfully created." }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1 or /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to host_url(@host), notice: "Host was successfully updated." }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1 or /hosts/1.json
  def destroy
    @host.destroy

    respond_to do |format|
      format.html { redirect_to hosts_url, notice: "Host was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_host
    @host = Host.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def host_params
    params.require(:host).permit(:title, :body, :age, :street)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_post, only: [:show, :edit, :update, :destroy]
  # *** CRUD Actions *** 7 methods - 4 methods are views

  # view
  def index
    @posts = Post.all
  end

  # view
  def show
    # @post = Post.find(params[:id])
  end

  # view
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "Post has been created!"
    else
      redirect_to new_post_path, notice: "Input fields have minimum lengths! Please try again!"
    end
  end

  # view
  def edit
    # @post = Post.find(params[:id])
  end

  def update
    # @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: "Post has been updated"
    else
      redirect_to edit_post_path(@post), notice: "Input fields have minimum lengths! Please try again!"
    end
  end

  def destroy
    # @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_url, notice: "Post: #{@post.title} is Deleted!"
  end

  private

  def get_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/costs/_cost.html.erb
<div id="<%= dom_id cost %>">
  <p>
    <strong>Title:</strong>
    <%= cost.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= cost.body %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= cost.age %>
  </p>

  <p>
    <strong>Fav color:</strong>
    <%= cost.fav_color %>
  </p>

</div>

app/views/costs/_form.html.erb
<section class="rounded mx-auto text-left p-3 pb-5 shadow-lg d-flex flex-column justify-content-center align-items-center" style="width: 18rem">
  <%= form_with(model: cost) do |form| %>
    <% if cost.errors.any? %>
      <div" style="color: red">
        <h2><%= pluralize(cost.errors.count, "error") %> prohibited this cost from being saved:</h2>
        <ul>
          <% cost.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>
    <div>
      <%= form.label :body, style: "display: block" %>
      <%= form.text_area :body %>
    </div>
    <div>
      <%= form.label :age, style: "display: block" %>
      <%= form.number_field :age %>
    </div>
    <div>
      <%= form.label :fav_color, style: "display: block" %>
      <%= form.text_field :fav_color %>
    </div>
    <div>
      <%= form.submit class: "mt-3 btn btn-dark w-100" %>
    </div>
  <% end %>
</section>

app/views/costs/edit.html.erb
<h1 class="text-center"
>Editing cost</h1>
<%= render "form", cost: @cost %>
<br>
<div class="w-100 mx-auto d-flex justify-content-center align-items-center gap-2">
  <%= link_to "Show this cost", @cost %> |
  <%= link_to "Back to costs", costs_path %>
</div>

app/views/costs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Costs</h1>

<div id="costs">
  <% @costs.each do |cost| %>
    <%= render cost %>
    <p>
      <%= link_to "Show this cost", cost %>
    </p>
  <% end %>
</div>

<%= link_to "New cost", new_cost_path %>

app/views/costs/new.html.erb
<h1 class="text-center">New cost</h1>
<%= render "form", cost: @cost %>
<br>
<div>
  <%= link_to "Back to costs", costs_path, class: "d-block text-center" %>
</div>

app/views/costs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cost %>

<div>
  <%= link_to "Edit this cost", edit_cost_path(@cost) %> |
  <%= link_to "Back to costs", costs_path %>

  <%= button_to "Destroy this cost", @cost, method: :delete %>
</div>

app/views/hosts/_form.html.erb
<%= form_with(model: host) do |form| %>
  <% if host.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(host.errors.count, "error") %> prohibited this host from being saved:</h2>
      <ul>
        <% host.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>
  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age, style: "width: 4rem", min: "1", max: "120" %>
  </div>
  <div>
    <%= form.label :street, style: "display: block" %>
    <%= form.text_field :street %>
  </div>
  <div>
    <%= form.submit class: "btn btn-dark my-2" %>
  </div>
<% end %>

app/views/hosts/_host.html.erb
<div id="<%= dom_id host %>">
  <p>
    <strong>Title:</strong>
    <%= host.title %>
  </p>
  <p>
    <strong>Body:</strong>
    <%= host.body %>
  </p>
  <p>
    <strong>Age:</strong>
    <%= host.age %>
  </p>
  <p>
    <strong>Street:</strong>
    <%= host.street %>
  </p>
</div>

app/views/hosts/edit.html.erb
<section class="text-center">
  <h1>Editing host</h1>
  <%= render "form", host: @host %>
  <br>
  <div>
    <%= link_to "Show this host", @host %> |
    <%= link_to "Back to hosts", hosts_path %>
  </div>
</section>

app/views/hosts/index.html.erb
<section class="text-center">
  <p style="color: green"><%= notice %></p>
  <h1>Hosts</h1>
  <div id="hosts">
    <% @hosts.each do |host| %>
      <%= render host %>
      <p>
        <%= link_to "Show this host", host %>
      </p>
    <% end %>
  </div>
  <%= link_to "New host", new_host_path %>
</section>

app/views/hosts/new.html.erb
<section class="text-center">
  <h1>New host</h1>
  <%= render "form", host: @host %>
  <br>
  <div>
    <%= link_to "Back to hosts", hosts_path %>
  </div>
</section>

app/views/hosts/show.html.erb
<section class="text-center">
  <p style="color: green"><%= notice %></p>
  <%= render @host %>
  <div>
    <%= link_to "Edit this host", edit_host_path(@host), class: "text-secondary" %> |
    <%= link_to "Back to hosts", hosts_path %>
    <%= button_to "Destroy this host", @host, method: :delete, class: "btn btn-danger" %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post_form.html.erb
<div class="text-center text-success"><%= notice %></div>
<%= form_for(@post) do |f| %>
  <div class="text-center">
    <p><%= f.text_field :title, placeholder: "Title ..." %></p>
    <p> <%= f.text_area :body, placeholder: "Text ..." %></p>
    <%= f.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1 class="text-center"><u>Edit Page</u></h1>
<%= render "posts/post_form" %>
<li class="text-center list-unstyled"><%= link_to "All Posts", root_path %></li>

app/views/posts/index.html.erb
<section class="w-100 mx-auto">
  <h1  class="text-center"><u>Index Page</u></h1>
  <div class="text-center text-danger"><%= notice %></div>
  <%= link_to "Create a New Post", new_post_path, class: "text-primary d-block my-5 text-center fs-6" %>
  <div class="w-100 m-auto d-flex justify-content-center align-items-center">
    <ul class="list-unstyled text-left">
      <% @posts.each do |p|%>
        <li><label><u>Id:</u></label> <span class="fs-5"><%= p.id %></span></li>
        <li><label><u>Title:</u></label> <%= p.title %></li>
        <li><label><u>Body:</u></label> <%= p.body %></li>
        <li><%= link_to "Show", post_path(p) %></li>
        <li><%= link_to "Edit", edit_post_path(p) %></li>
        <li><%= link_to "Delete", post_path(p),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
        <hr class="m-auto my-2" style="box-shadow: 0 5px 5px #000">
      <% end %>
    </ul>
  </div>
</section>

app/views/posts/new.html.erb
<h1 class="text-center"><u>New Page</u></h1>
<%= render "posts/post_form" %>
<%= link_to "Home", root_path, class: "d-block text-center my-2" %>

app/views/posts/show.html.erb
<h1 class="text-center"><u>Show Page</u></h1>
<div class="text-center text-success"><%= notice %>
</div>
<div class="text-center">
  <p><u>Title:</u> <%= @post.title %></p>
  <p><u>Body:</u> <%= @post.body %></p>
</div>
<ul class="list-unstyled text-center">
  <li><%= link_to "Edit", edit_post_path(@post) %></li>
  <li><%= link_to "All Posts", root_path %></li>
</ul>